### ISSUE TITLE
Task 6 : clock management

### ISSUE THREAD

**Issue by Spriithy** [busychess/Assisted-Board-Games#20]

**Comment by MarylineChen** [comment]
Deux solutions possibles : 
1) En temps brut (chaque joueur a x mins) : on rajoute à la partie le timestamp de départ et pour chaque coup son timestamp associé. On calcule le temps d'un joueur en faisant la différence entre le le timestamp de départ (de la partie)  et le timestamp son dernier coup joué

2) Horloge avec incrément (15|10, c-à-d qu'on a 15 mins par joueur et un gain de 10s par coup joué) : à chaque coup, on fait la différence pour avoir le temps joué et on incrément le temps restant (de 10s).

**Comment by Spriithy** [comment]
Pour la solution 1. il faut bien penser à soustraire tous le temps passé par l'autre joueur ! sinon on obtient le temps total de la partie...

La solution la plus simple à mon sens serait d'uniquement faire la solution 2 (en prenant en compte le temps de l'adversaire aussi) mais en utilisant un incrément de 0 dans le cas d'une horloge sans incrément.
