### ISSUE TITLE
Create chess puzzle model 

### ISSUE THREAD

**Issue by Spriithy** [busychess/Assisted-Board-Games#21]

**Comment by Spriithy** [comment]
Bonjour Monsieur @oliviercailloux,

Nous aurions aimé discuter avec vous de comment gérer les puzzles du côté serveur. Doit-on uniquement pouvoir en ajouter via des endpoints de l'API ou aussi via des fichiers json depuis les resources du projet ?

**Comment by oliviercailloux** [comment]
Pas sûr de comprendre votre question. Mais il me semble qu’il y a matière à plusieurs tâches. À vous de proposer une découpe. 

Je commencerais par une possibilité de définir un puzzle dans le code, à savoir, un GameState où les clocks n’auraient pas d’importance. Il suffit d’ajouter une possibilité d’indiquer une durée très grande dans la documentation (cf. Duration). Ensuite, il vous faut j’imagine étendre GameEntity de façon à pouvoir commencer la partie avec un état spécifié. Un puzzle consiste donc en un GameState et un ensemble de coups (qui arrivent à un objectif t.q. le mat ou la prise d’une pièce). Il faut ensuite un moyen de représenter une telle GameEntity en json (ça devrait déjà être à peu près possible). Et un accès REST à ces puzzles (ajout et lecture). Il est ensuite facile de permettre d’avoir dans les ressources serveur certains json qui définissent des puzzles de base (ou des parties, plus généralement). Ajoutez et peaufinez comme il vous semble bon.
