### ISSUE TITLE
Create Board object in place of fen strings

### ISSUE THREAD

**Issue by Spriithy** [busychess/Assisted-Board-Games#64]

**Comment by elbaylot** [comment]
Bonjour @oliviercailloux,

@Spriithy m'a expliqué l'objet de cette fonctionnalité. Cependant, je ne vois pas comment faire en sorte d'imbriquer dans l'architecture actuelle un tel objet. Je ne vois pas comment on peut faire autrement que  garder le FEN string dans l'objet et de fait Board ne serait qu'un wrapper autour de ce string.

Y voyez vous autre chose ?

**Comment by oliviercailloux** [comment]
Je ferais un `BoardEntity`, immuable, qui contient un `Board` (de la bibliothèque sur laquelle vous vous appuyez) et un `String` (sa représentation FEN, uniquement pour enregistrement en base SQL), qui sert également de clé unique (à moins que vous vouliez mettre autre chose dedans).

Le String est considéré comme un détail d’implémentation (on pourrait changer la manière dont on sauvegarde les instances en base), donc caché des utilisateurs. `BoardEntity` contient une méthode publique `asBoard(): Board`, et un constructeur statique public à partir d’un `Board` et un à partir d’un FEN (et peut-être d’autres si vous voulez accepter d’autres modes de représentation, par exemple un constructeur à partir de Json serait très utile ; voir idéalement s’il existe déjà une représentation standard d’un plateau d’échecs en Json, le contraire m’étonnerait, mais cela ferait l’objet d’une tâche facultative et indépendante). Le reste est privé ou accessible seulement à JPA.

**Comment by elbaylot** [comment]
Très bien, je me penche sur cela. merci

**Comment by oliviercailloux** [comment]
À la réflexion, `ChessBoard` serait un meilleur nom : on ne veut pas mettre particulièrement en avant que cet objet est une entité, car on pourrait très bien utiliser autre chose que JPA pour la sauvegarde en base (par ex. tout sauvegarder en Json). (Le meilleur nom serait `Board`, mais il est pris.)
